version: '3'

services:
  se-api:
    image: gaufoo/se-api
    ports:
      - '8500:8500'
    depends_on:
      - 'se-db'
    environment:
      WAIT_HOSTS: se-db:3306
    restart: always

  se-front:
    image: gaufoo/se-front
    ports:
      - '8000:80'
    depends_on:
      - 'se-api'
    environment:
      WAIT_HOSTS: se-db:3306
    restart: always

  se-db:
    image: mysql:5.7
    environment:
      MYSQL_USER: rjgc
      MYSQL_PASSWORD: rjgc123
      MYSQL_DATABASE: rjgc7484
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always

