version: "3"
services:
  front:
    image: gaufoo/se-front
    ports:
      - "1234:80"
    depends_on:
      - "api"
    restart: always
  api:
    image: gaufoo/se-api
    ports:
      - "4567:4567"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    depends_on:
      - "mysql"
    restart: always
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - data
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always
